### ISSUE TITLE
Feature Request: Random number generation

### ISSUE THREAD

**Issue by patrickheney** [MeridiusIX/RivalAI#191]
Suggested syntax: R(#,#)
Usage: anywhere that currently accepts a number

Example
[IdealPlanetAltitude:R(1000,3000)]

**Comment by MeridiusIX** [comment]
While I like the idea, it wouldn't be feasible to implement. RivalAI pre-processes all the profiles at game start, and then creates copies from serialized data. Because of this, if the values were randomized, then they'd randomize once at startup and be that way for the remainder of the game session. Reworking the code to allow that to work properly is too much work.
